# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "MiVTslFippWCRWFq0vjnTkFdAk4A7vdNtyZ6Ugt13U2Fr7JDWWpsdse//JiNE1GT5bXpK7k2lNX/DA4iUHuQpQmOLZN7oHV5zuaX7Ym8XqI8WurVI80Oyh+004kQXRq3+XneRsrQfvP7YosIeNm87v4AF+bJzVcV2/v3YKnaeOvcmf27phnEcv01mY6iHZ+TufvBZAPoIUv3Fg87PV9OWNzdvTL/Hh4skNZt+gPdRR+zMd7Oh+nJ2m0ZYR5e0qwVdp+QBUDy+RYjTp8v9qnY7MdOmBffdNOTGVrQMPIEn8meIOO6xcq9vbGFqnXjCG/wu7vCaymVSzGhEyi3XnmYyhFwnooOvkCgRJMlAq09UAs+u3qXxRrTPBXw8pVA6tldOAkOa2RPEA4gkBvYeGX9hHVcam2M+Lbq0N1EmmusL3GVchyt30WGmZyy/j91JI0vlRAw5j1W1JUFlg/CEB66MVUPUlID3XD1PjmlrGSggQU0ODnyc6NKAJYIsyufDSELw0OJLJhzxj1Y3KUE3TSHPHLhp7yNN3L3ASpe9K+aGfuK6etV3G26XFemyFOHrSvtwu4xjM+hL4PPEWWBfuukJ+/o128rBKh5rHOK9jH7enos1f1pOBOOmEwc+wzrjViwx5WFlrLXa/SWCZnN5tcstFbaSlFKjhWkuNhLVIgF2Gg="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
