travis:
  secure:
    BINSTAR_TOKEN: Y3pouJIIGdK67yu9sApwDCNnPQrpVpiDpPf9vXv/gtQojUqC5gQAU86L2MojZXTylABpler/s23X/Z8vi28qS9ZxogL19dxxbumUHSBZkcPMSE/B8q/gUe1OET/BzLUE+VpM7UQN8gRH5mel5KnLssN7S7L2VUeqsh4djzfC/141toxMfbKE4URGgxBDKktS/CfsMWpK3oYiib89IFa+y7Y6quK1HEQGvg3N3Zk+qNrEa7Ufgro8FQcXlUubCaH1Xs/7yCRCVhvgaX2dUgd9jTeCSzo2TwY/i3kG8/PCBtT6r/6zWVcjp2H7ISpzxMi1lJmRe3hXRd1jlkaGJxwJG3ksVutQNRN1M/bylaoCry5FAJLZXs1w+qoLLddC+eqHCCeP38ltUhEq4u6ekkDnuqZkbzWqZQpUx9RvbLi/cvTDzaN8wSoCvd6RY4tJNzpJA9cXOS9Kp8m4KV3u5PFi0hCxAci/WjKpHY8b3kEm+IFD2qM4srNFjVdGGupP8KjpeFmnWjlBsCXoq2DQ3nXZTtn0FeWKc1SxukC5GRxoewA3VUGqN8MpxIHCOn16iBSctVR/jv9ffRNVLpRgzoSU/bP5bJ9LZ2H0nAFtlh+ygHjFCVfmfGXXztJ0aRigJq4TJZHP2M98AzIikPMpiQ0ZCWKA0IeH+bEmQUMpKDhUuSs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
