travis:
  secure:
    BINSTAR_TOKEN: tAWfbhHpI4aAk6OaHMHnTC2HtDeqsCs/Dg8RZIWg6k4qY2SdMKH5Pe+c4AbuLlG3ITNiCCxDez8HOUZDGdTYdw2Szo4ngRl0DoBgsVoZRDl4TAn8uahcGP56aV/s+tjtlTS2CmIRfN7TohIU5GQcmz75lBjWefU+WdcLtyR6G62lJUdtahr7MPv2Nb8FNCsymolQECcLxz+AB3/b0G8KSa/NyCe+fG7JA8J2A9QpUj9lhCfLBSTych5Nemslpv2c/Gb1IxS3yV+ipwA3Ye3PJjL1Vp3901/CF67X60oDTztNdINmtNT31ha1ZqbubV/gODV2Znx35YqDLt9cwtvDCYiIwlTaLof70XuqAZvdZqY2reyWpAFiwZS7oe6VsfOqH/P0vzADI348iiKbY+O9bONpdIpGYxO4G3PQtcUmqh5Z1h3f0ztKm44wElc1k/FCPdP7zNgmBDdfnsUXcIkh3bkceNiGfD41YobLO/mSEsiTXVPBffNemn9lGsgeW5fxDHzQtQBBoZVNScoZfIDSWfktIXF0Q4o5At5ub9JdVxUFwaMos+4PgNhK9l1Hj8VJdRnU/am9THqyRRkONqhmFaTMrM7YkHKzkrZkV7H0YvcfJ5SKfkfQIBcsBZC5a2YZkvXSEJLpFDIGP3l9UAjFYndPCl5yOkKxpjRdVlktrfA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
