travis:
  secure:
    BINSTAR_TOKEN: MiVTslFippWCRWFq0vjnTkFdAk4A7vdNtyZ6Ugt13U2Fr7JDWWpsdse//JiNE1GT5bXpK7k2lNX/DA4iUHuQpQmOLZN7oHV5zuaX7Ym8XqI8WurVI80Oyh+004kQXRq3+XneRsrQfvP7YosIeNm87v4AF+bJzVcV2/v3YKnaeOvcmf27phnEcv01mY6iHZ+TufvBZAPoIUv3Fg87PV9OWNzdvTL/Hh4skNZt+gPdRR+zMd7Oh+nJ2m0ZYR5e0qwVdp+QBUDy+RYjTp8v9qnY7MdOmBffdNOTGVrQMPIEn8meIOO6xcq9vbGFqnXjCG/wu7vCaymVSzGhEyi3XnmYyhFwnooOvkCgRJMlAq09UAs+u3qXxRrTPBXw8pVA6tldOAkOa2RPEA4gkBvYeGX9hHVcam2M+Lbq0N1EmmusL3GVchyt30WGmZyy/j91JI0vlRAw5j1W1JUFlg/CEB66MVUPUlID3XD1PjmlrGSggQU0ODnyc6NKAJYIsyufDSELw0OJLJhzxj1Y3KUE3TSHPHLhp7yNN3L3ASpe9K+aGfuK6etV3G26XFemyFOHrSvtwu4xjM+hL4PPEWWBfuukJ+/o128rBKh5rHOK9jH7enos1f1pOBOOmEwc+wzrjViwx5WFlrLXa/SWCZnN5tcstFbaSlFKjhWkuNhLVIgF2Gg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
