travis:
  secure:
    BINSTAR_TOKEN: ViL01hJvlRdAIY5BjQgQ85QkNGYAiiDI6EMDW4F7GRvBfN4XWqpDbJufe8cOYXvcK+okuCQyVBBsamTViL05n+ghVE5IkVMdVOPoEzy9vjbem1q6yvqDRZ3aPV7HyO8baewgGJ5vwKwnFaRnWCYawM+4lVndSnPVlmMD/BAg+QQV9UB4u/lo5J0zkEkJ2n+64kGHbL5RnEnrP257ZlZYpRDlUkCilIG/FA04L5k6Ee6IsGSvUe9rBr60ATAmlg1mNNxEr56TSwp92lEq2IGH48nbhBg4tGZ5d8NvnpS/WMUu1ul9XKg5RpohR12N62ZAXnHl4sD/cNmwaOq7xd1cwLClOaCUuILAlOZH24BgBEOJWUt6LzZ0FcFMU/8icCVF6qASJl3xAs+DuudC8DtxJEmoD2YAgxG4+sZzujbB/2n6z05kl7Sgq3Vo+jzrQWYOjyhnnTgwv1d76NWzEtZij8sb/TZ8c1QamCJE2xzQX5z/9khKKVSE1WPwni8i39AmwnHO6jB+0EZSdxvFhNmvV00LTdgHASByxVMWB1Xhd58Y+d/dGzojOOgtMVrUHbR9UMRNm/SN5HyIpS5tqNyPiJMzo9abewiDowJiTkBH9WTodqGsTfkBmgYn/PAUOLvAU5eOHpwA6f71H76z1krEexMN29WYfCTEtAUXA5T5Afk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
